name: deploy-kubemanifest

on:
  push:
    branches:
      - prod
    paths:
      - 'A/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.MARKETPLACE_CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save marketplace-k8

      - name: Deploy manifests to Kubernetes
        run: kubectl apply -f A/k8s-prod
